apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recifeed-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: recifeed.example.com
    http:
      paths:
      - path: /bsky
        pathType: Prefix
        backend:
          service:
            name: bsky-service
            port:
              number: 80
      - path: /twitter
        pathType: Prefix
        backend:
          service:
            name: twitter-service
            port:
              number: 80
      - path: /recipe-query
        pathType: Prefix
        backend:
          service:
            name: recipe-query-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: monolith
            port:
              number: 80